#!/usr/bin/env node

var host = "0.0.0.0"
var port = 1621
var opts = {}

var web = require('glagol-web')
var resolve = require('path').resolve
var server = web.server(host, port, {
  0: web.app(opts, resolve(__dirname, './src'))
})

server.http.on('listening', function () {
  console.log('open ' + host + ':' + port + ' in default browser')
})
